version: '2'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - './app:/app'
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - './db:/docker-entrypoint-initdb.d'