version: '2'
services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - "./app:/app"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/*.sql:/docker-entrypoint-initdb.d