version: '2'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - './src:/app'
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - '.src/db/tools:/docker-entrypoint-initdb.d'